---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/table
  label: Table
  create: documents
  match: "**/*"
  templates:
  - table-template
- type: directory
  path: src/content/chapo
  label: Chapô
  create: documents
  match: "**/*"
  templates:
  - chapo-template
- type: directory
  path: src/content/navBar
  label: Nav bar
  create: documents
  match: "**/*"
  templates:
  - nav-bar-template
- type: directory
  path: src/content/hero
  label: Hero
  create: documents
  match: "**/*"
  templates:
  - hero-template
upload_dir: src/uploads
public_path: "../uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
